# Generated by Django 2.0.6 on 2018-06-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSysMessageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_message_set_name', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('display_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PLAccount',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('commentary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('village_no', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=255)),
                ('discription', models.TextField(blank=True)),
                ('start_class', models.SmallIntegerField(choices=[(1, '自動'), (2, '手動'), (3, '定員')], default=1)),
                ('lowest_number', models.IntegerField()),
                ('into_password', models.CharField(max_length=255)),
                ('update_time', models.TimeField()),
                ('update_interval', models.SmallIntegerField(choices=[(24, '24時間'), (48, '48時間'), (72, '72時間')], default=24)),
                ('start_scheduled_date', models.DateField()),
                ('abolition_date', models.DateField()),
                ('voice_number_class', models.SmallIntegerField(choices=[(1, '回数制'), (2, 'ポイント(pt)制')], default=1)),
                ('system_message_no', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='pywolf.MSysMessageSet')),
                ('village_master_id', models.ForeignKey(on_delete=models.SET('削除されたID'), to='pywolf.PLAccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
