# Generated by Django 2.0.6 on 2018-06-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0002_auto_20180626_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MSysMessageSet',
            new_name='MasterSystemMessageSet',
        ),
    ]
