# Generated by Django 2.0.6 on 2018-06-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0003_auto_20180626_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterSystemMessageSet',
            new_name='MSysMessageSet',
        ),
    ]
