# Generated by Django 2.0.6 on 2018-06-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0004_auto_20180626_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='MChip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('description', models.CharField(max_length=30)),
                ('character_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MChipSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_set_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('image_file_path', models.FilePathField()),
                ('character_number', models.SmallIntegerField()),
                ('animation_flg', models.BooleanField(default=False)),
                ('description_change_enable_flg', models.BooleanField(default=False)),
                ('character_name_change_enable_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MOrganizationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_set_name', models.CharField(max_length=100)),
                ('participant_number', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('camp_class', models.SmallIntegerField(choices=[(1, '村人'), (2, '人狼')], default=1)),
                ('vote_enable_flg', models.BooleanField(default=True)),
                ('fortune_enable_flg', models.BooleanField(default=False)),
                ('spirit_enable_flg', models.BooleanField(default=False)),
                ('guard_enable_flg', models.BooleanField(default=False)),
                ('share_enable_flg', models.BooleanField(default=False)),
                ('assault_enable_flg', models.BooleanField(default=False)),
                ('commentary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MPositionVoiceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_hear_mode', models.SmallIntegerField(choices=[(0, '発言・閲覧不可'), (1, '発言不可・他人発言のみ閲覧可'), (2, '発言可・自己発言のみ閲覧可'), (3, '発言可・自己・他人発言ともに可')], default=0)),
                ('commentary', models.TextField()),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MPosition')),
            ],
        ),
        migrations.CreateModel(
            name='MSysMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.SmallIntegerField()),
                ('system_message_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('system_message_set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MSysMessageSet')),
            ],
        ),
        migrations.CreateModel(
            name='MVoiceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_number', models.SmallIntegerField()),
                ('voice_point', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MVoiceSettingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type_set_name', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('display_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MVoiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type_name', models.CharField(max_length=100)),
                ('voice_type_symbol', models.CharField(max_length=10)),
                ('prologue_speech_enable_flg', models.BooleanField()),
                ('commentary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VillageOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.SmallIntegerField()),
                ('number', models.SmallIntegerField()),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition')),
            ],
        ),
        migrations.CreateModel(
            name='VillageParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('character_name', models.CharField(max_length=30)),
                ('status', models.SmallIntegerField(choices=[(0, '生存'), (1, '処刑死'), (2, '襲撃死'), (9, '突然死')], default=0)),
                ('win_lose_class', models.SmallIntegerField(choices=[(0, '未決着'), (1, '勝利'), (2, '敗北'), (9, '突然死')], default=0)),
                ('memo', models.TextField()),
                ('chip_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MChip')),
                ('pl_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.PLAccount')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_position_id', to='pywolf.MPosition')),
            ],
        ),
        migrations.CreateModel(
            name='VillageParticipantExeAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.SmallIntegerField(default=0)),
                ('assault_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_assault_id', to='pywolf.PLAccount')),
                ('fortune_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_fortune_id', to='pywolf.PLAccount')),
                ('guard_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_guard_id', to='pywolf.PLAccount')),
                ('village_participant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant')),
                ('vote_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_vote_id', to='pywolf.PLAccount')),
            ],
        ),
        migrations.CreateModel(
            name='VillageParticipantVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.SmallIntegerField(default=0)),
                ('voice_number', models.SmallIntegerField()),
                ('use_point', models.SmallIntegerField()),
                ('voice_datetime', models.DateTimeField()),
                ('good_pl_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.PLAccount')),
                ('village_participant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant')),
                ('voice_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType')),
            ],
        ),
        migrations.CreateModel(
            name='VillageParticipantVoiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.SmallIntegerField(default=0)),
                ('voice_number_remain', models.SmallIntegerField()),
                ('voice_point_remain', models.SmallIntegerField()),
                ('village_participant_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant')),
                ('voice_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType')),
            ],
        ),
        migrations.CreateModel(
            name='VillageProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_no', models.SmallIntegerField(default=0)),
                ('village_status', models.SmallIntegerField(choices=[(0, 'プロローグ'), (1, '進行中'), (2, 'エピローグ'), (3, '終了'), (4, '廃村')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VillageVoiceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_number', models.SmallIntegerField()),
                ('voice_point', models.SmallIntegerField()),
                ('prologue_limit_off_flg', models.BooleanField()),
                ('tomb_limit_off_flg', models.BooleanField()),
                ('epilogue_limit_off_flg', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='village',
            old_name='village_master_id',
            new_name='village_master_account',
        ),
        migrations.AlterField(
            model_name='village',
            name='lowest_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='village',
            name='system_message_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MSysMessageSet'),
        ),
        migrations.AddField(
            model_name='villagevoicesetting',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
        ),
        migrations.AddField(
            model_name='villagevoicesetting',
            name='voice_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType'),
        ),
        migrations.AddField(
            model_name='villageprogress',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
        ),
        migrations.AddField(
            model_name='villageparticipant',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
        ),
        migrations.AddField(
            model_name='villageparticipant',
            name='wish_position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_wish_position_id', to='pywolf.MPosition'),
        ),
        migrations.AddField(
            model_name='villageorganization',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
        ),
        migrations.AddField(
            model_name='mvoicesetting',
            name='voice_setting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MVoiceSettingSet'),
        ),
        migrations.AddField(
            model_name='mvoicesetting',
            name='voice_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType'),
        ),
        migrations.AddField(
            model_name='mpositionvoicesetting',
            name='voice_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MVoiceType'),
        ),
        migrations.AddField(
            model_name='morganization',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MOrganizationSet'),
        ),
        migrations.AddField(
            model_name='morganization',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition'),
        ),
        migrations.AddField(
            model_name='mchip',
            name='chip_set_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MChipSet'),
        ),
        migrations.AlterUniqueTogether(
            name='villagevoicesetting',
            unique_together={('village_no', 'voice_type_id')},
        ),
        migrations.AlterUniqueTogether(
            name='villageprogress',
            unique_together={('village_no', 'day_no')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantvoicestatus',
            unique_together={('village_participant_id', 'day_no')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantvoice',
            unique_together={('village_participant_id', 'day_no', 'voice_type_id', 'voice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantexeability',
            unique_together={('village_participant_id', 'day_no')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipant',
            unique_together={('village_no', 'pl_id')},
        ),
        migrations.AlterUniqueTogether(
            name='villageorganization',
            unique_together={('village_no', 'serial_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mvoicesetting',
            unique_together={('voice_setting_id', 'voice_type_id')},
        ),
        migrations.AlterUniqueTogether(
            name='msysmessage',
            unique_together={('system_message_set_id', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mpositionvoicesetting',
            unique_together={('position_id', 'voice_type_id')},
        ),
        migrations.AlterUniqueTogether(
            name='morganization',
            unique_together={('organization_id', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mchip',
            unique_together={('chip_set_id', 'sequence_number')},
        ),
    ]
