# Generated by Django 2.0.6 on 2018-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0006_auto_20180630_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchipset',
            name='image_file_path',
            field=models.FileField(upload_to='chips/'),
        ),
        migrations.AlterField(
            model_name='village',
            name='into_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='lowest_number',
            field=models.SmallIntegerField(default=10),
        ),
    ]
