# Generated by Django 2.0.6 on 2018-07-03 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0007_auto_20180630_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='chip_set_id',
            new_name='chip_set',
        ),
        migrations.RenameField(
            model_name='village',
            old_name='system_message_id',
            new_name='system_message',
        ),
        migrations.RenameField(
            model_name='villageorganization',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='villageparticipant',
            old_name='chip_id',
            new_name='chip',
        ),
        migrations.RenameField(
            model_name='villageparticipant',
            old_name='pl_id',
            new_name='pl',
        ),
        migrations.RenameField(
            model_name='villageparticipant',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='villageparticipant',
            old_name='wish_position_id',
            new_name='wish_position',
        ),
        migrations.RenameField(
            model_name='villageparticipantexeability',
            old_name='assault_id',
            new_name='assault',
        ),
        migrations.RenameField(
            model_name='villageparticipantexeability',
            old_name='fortune_id',
            new_name='fortune',
        ),
        migrations.RenameField(
            model_name='villageparticipantexeability',
            old_name='guard_id',
            new_name='guard',
        ),
        migrations.RenameField(
            model_name='villageparticipantexeability',
            old_name='village_participant_id',
            new_name='village_participant',
        ),
        migrations.RenameField(
            model_name='villageparticipantexeability',
            old_name='vote_id',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='villageparticipantvoice',
            old_name='good_pl_id',
            new_name='good_pl',
        ),
        migrations.RenameField(
            model_name='villageparticipantvoice',
            old_name='village_participant_id',
            new_name='village_participant',
        ),
        migrations.RenameField(
            model_name='villageparticipantvoice',
            old_name='voice_type_id',
            new_name='voice_type',
        ),
        migrations.RenameField(
            model_name='villageparticipantvoicestatus',
            old_name='village_participant_id',
            new_name='village_participant',
        ),
        migrations.RenameField(
            model_name='villageparticipantvoicestatus',
            old_name='voice_type_id',
            new_name='voice_type',
        ),
        migrations.RenameField(
            model_name='villagevoicesetting',
            old_name='voice_type_id',
            new_name='voice_type',
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='day_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageProgress'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='day_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageProgress'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='day_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageProgress'),
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipant',
            unique_together={('village_no', 'pl')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantexeability',
            unique_together={('village_participant', 'day_no')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantvoice',
            unique_together={('village_participant', 'day_no', 'voice_type', 'voice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantvoicestatus',
            unique_together={('village_participant', 'day_no')},
        ),
        migrations.AlterUniqueTogether(
            name='villagevoicesetting',
            unique_together={('village_no', 'voice_type')},
        ),
    ]
