# Generated by Django 2.0.6 on 2018-07-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0008_auto_20180703_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mchip',
            old_name='chip_set_id',
            new_name='chip_set',
        ),
        migrations.RenameField(
            model_name='morganization',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='mpositionvoicesetting',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='mpositionvoicesetting',
            old_name='voice_type_id',
            new_name='voice_type',
        ),
        migrations.RenameField(
            model_name='msysmessage',
            old_name='system_message_set_id',
            new_name='system_message_set',
        ),
        migrations.RenameField(
            model_name='mvoicesetting',
            old_name='voice_setting_id',
            new_name='voice_setting',
        ),
        migrations.RenameField(
            model_name='mvoicesetting',
            old_name='voice_type_id',
            new_name='voice_type',
        ),
        migrations.AlterUniqueTogether(
            name='mchip',
            unique_together={('chip_set', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='morganization',
            unique_together={('organization', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mpositionvoicesetting',
            unique_together={('position', 'voice_type')},
        ),
        migrations.AlterUniqueTogether(
            name='msysmessage',
            unique_together={('system_message_set', 'sequence_number')},
        ),
        migrations.AlterUniqueTogether(
            name='mvoicesetting',
            unique_together={('voice_setting', 'voice_type')},
        ),
    ]
