# Generated by Django 2.0.6 on 2018-07-03 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0009_auto_20180703_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='voice_type_symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='good_pl',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pywolf.PLAccount'),
        ),
    ]
