# Generated by Django 2.0.6 on 2018-07-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0010_auto_20180703_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageparticipantvoice',
            name='voice',
            field=models.TextField(blank=True),
        ),
    ]
