# Generated by Django 2.0.6 on 2018-07-03 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0011_villageparticipantvoice_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchip',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mchipset',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morganizationset',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mposition',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msysmessage',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='msysmessageset',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mvoicesettingset',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mvoicetype',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placcount',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villageparticipant',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villageparticipantvoice',
            name='delete_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villageparticipantvoice',
            name='village_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/chips/'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '生存'), (1, '処刑死'), (2, '襲撃死'), (9, '突然死'), (10, '退村')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipantvoice',
            unique_together={('village_no', 'day_no', 'voice_type', 'voice_number')},
        ),
    ]
