# Generated by Django 2.0.6 on 2018-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0012_auto_20180703_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='day_no',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='day_no',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='day_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
