# Generated by Django 2.0.6 on 2018-07-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0013_auto_20180703_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='placcount',
            name='id_view',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villageparticipant',
            name='village_denominated_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='sequence_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='character_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='sequence_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='speech_hear_mode',
            field=models.SmallIntegerField(choices=[(0, '発言・閲覧不可'), (1, '発言不可・他人発言のみ閲覧可'), (2, '発言可・自己発言のみ閲覧可'), (3, '発言可・自己・他人発言ともに閲覧可')], default=0),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='sequence_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_point',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mvoicesettingset',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='prologue_speech_enable_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='commentary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='assault',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_assault_id', to='pywolf.PLAccount'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='fortune',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_fortune_id', to='pywolf.PLAccount'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='guard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_guard_id', to='pywolf.PLAccount'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='vote',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipantexeability_vote_id', to='pywolf.PLAccount'),
        ),
    ]
