# Generated by Django 2.0.6 on 2018-07-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0014_auto_20180711_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='assault',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='fortune',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='guard',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='vote',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='good_pl',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
