# Generated by Django 2.0.6 on 2018-07-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0015_auto_20180717_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='placcount',
            name='system_user_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villageparticipant',
            name='system_user_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='villageparticipantvoice',
            name='system_voice_flg',
            field=models.BooleanField(default=False),
        ),
    ]
