# Generated by Django 2.0.6 on 2018-07-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0016_auto_20180721_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageparticipantvoice',
            name='voice_order',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
