# Generated by Django 2.0.6 on 2018-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0017_villageparticipantvoice_voice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvoicesetting',
            name='max_str_length',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mvoicesetting',
            name='max_voice_point',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagevoicesetting',
            name='max_str_length',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='villagevoicesetting',
            name='max_voice_point',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='epilogue_limit_off_flg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='prologue_limit_off_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='tomb_limit_off_flg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='voice_number',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='voice_point',
            field=models.SmallIntegerField(default=0),
        ),
    ]
