# Generated by Django 2.0.6 on 2018-08-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0018_auto_20180722_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mchipset',
            name='image_file_path',
        ),
        migrations.AddField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(default=1, upload_to='pywolf/chips/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mchip',
            name='image_height',
            field=models.SmallIntegerField(default=130),
        ),
        migrations.AddField(
            model_name='mchip',
            name='image_width',
            field=models.SmallIntegerField(default=90),
        ),
    ]
