# Generated by Django 2.0.6 on 2018-09-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0019_auto_20180802_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageOrganizationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_set_name', models.CharField(max_length=100)),
                ('participant_number', models.SmallIntegerField()),
                ('delete_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='village',
            name='max_number',
            field=models.SmallIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/chips/'),
        ),
        migrations.AddField(
            model_name='villageorganizationset',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village'),
        ),
        migrations.AddField(
            model_name='villageorganization',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pywolf.VillageOrganizationSet'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='villageorganization',
            unique_together={('village_no', 'organization', 'serial_number')},
        ),
        migrations.AlterUniqueTogether(
            name='villageorganizationset',
            unique_together={('village_no', 'organization_set_name')},
        ),
    ]
