# Generated by Django 2.1.2 on 2018-10-26 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0021_auto_20181026_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': '村', 'verbose_name_plural': '村情報'},
        ),
        migrations.AlterField(
            model_name='placcount',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID(内部)'),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='id_view',
            field=models.CharField(max_length=100, verbose_name='ID(表示用)'),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='password',
            field=models.CharField(max_length=255, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='placcount',
            name='system_user_flg',
            field=models.BooleanField(default=False, verbose_name='システム用ユーザーフラグ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='abolition_date',
            field=models.DateField(verbose_name='廃村日'),
        ),
        migrations.AlterField(
            model_name='village',
            name='chip_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MChipSet', verbose_name='チップセット'),
        ),
        migrations.AlterField(
            model_name='village',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='description',
            field=models.TextField(blank=True, verbose_name='村説明'),
        ),
        migrations.AlterField(
            model_name='village',
            name='into_password',
            field=models.CharField(blank=True, max_length=255, verbose_name='入村パスワード'),
        ),
        migrations.AlterField(
            model_name='village',
            name='lowest_number',
            field=models.SmallIntegerField(default=10, verbose_name='最低人数'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/chips/'),
        ),
        migrations.AlterField(
            model_name='village',
            name='max_number',
            field=models.SmallIntegerField(default=16, verbose_name='最大人数'),
        ),
        migrations.AlterField(
            model_name='village',
            name='start_class',
            field=models.SmallIntegerField(choices=[(1, '自動'), (2, '手動'), (3, '定員')], default=1, verbose_name='開始区分'),
        ),
        migrations.AlterField(
            model_name='village',
            name='start_scheduled_date',
            field=models.DateField(verbose_name='村開始予定日'),
        ),
        migrations.AlterField(
            model_name='village',
            name='system_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MSysMessageSet', verbose_name='システム文章'),
        ),
        migrations.AlterField(
            model_name='village',
            name='update_interval',
            field=models.SmallIntegerField(choices=[(24, '24時間'), (48, '48時間'), (72, '72時間')], default=24, verbose_name='更新間隔'),
        ),
        migrations.AlterField(
            model_name='village',
            name='update_time',
            field=models.TimeField(verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_master_account',
            field=models.ForeignKey(on_delete=models.SET('削除されたID'), to='pywolf.PLAccount', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_name',
            field=models.CharField(max_length=255, verbose_name='村名'),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='村No'),
        ),
        migrations.AlterField(
            model_name='village',
            name='voice_number_class',
            field=models.SmallIntegerField(choices=[(1, '回数制'), (2, 'ポイント(pt)制')], default=1, verbose_name='発言数区分'),
        ),
    ]
