# Generated by Django 2.1.2 on 2018-10-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0022_auto_20181026_1401'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='village',
        #     name='max_number',
        #     field=models.SmallIntegerField(default=16, verbose_name='最大人数'),
        # ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/chips/'),
        ),
    ]
