# Generated by Django 2.1.2 on 2018-10-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0023_auto_20181026_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchip',
            name='character_name',
            field=models.CharField(max_length=30, verbose_name='キャラクタ名'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='chip_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MChipSet', verbose_name='チップセット'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='description',
            field=models.CharField(max_length=30, verbose_name='肩書'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/chips/', verbose_name='画像ファイルパス'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_height',
            field=models.SmallIntegerField(default=130, verbose_name='画像高さ'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_width',
            field=models.SmallIntegerField(default=90, verbose_name='画像幅'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='sequence_number',
            field=models.SmallIntegerField(default=0, verbose_name='連番'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='animation_flg',
            field=models.BooleanField(default=False, verbose_name='アニメーションフラグ'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='作者名'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='character_name_change_enable_flg',
            field=models.BooleanField(default=False, verbose_name='キャラクタ名変更可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='character_number',
            field=models.SmallIntegerField(default=0, verbose_name='キャラクター人数'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='chip_set_name',
            field=models.CharField(max_length=100, verbose_name='チップセット名称'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='mchipset',
            name='description_change_enable_flg',
            field=models.BooleanField(default=False, verbose_name='肩書き変更可否フラグ'),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='number',
            field=models.SmallIntegerField(verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MOrganizationSet', verbose_name='編成セット'),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition', verbose_name='役職ID'),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='sequence_number',
            field=models.SmallIntegerField(default=0, verbose_name='連番'),
        ),
        migrations.AlterField(
            model_name='morganizationset',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='morganizationset',
            name='organization_set_name',
            field=models.CharField(max_length=100, verbose_name='編成セット名称'),
        ),
        migrations.AlterField(
            model_name='morganizationset',
            name='participant_number',
            field=models.SmallIntegerField(verbose_name='参加者数'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='assault_enable_flg',
            field=models.BooleanField(default=False, verbose_name='襲撃可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='camp_class',
            field=models.SmallIntegerField(choices=[(1, '村人'), (2, '人狼')], default=1, verbose_name='陣営区分'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='commentary',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='fortune_enable_flg',
            field=models.BooleanField(default=False, verbose_name='占い可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='guard_enable_flg',
            field=models.BooleanField(default=False, verbose_name='護衛可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='position_name',
            field=models.CharField(max_length=100, verbose_name='役職名称'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='share_enable_flg',
            field=models.BooleanField(default=False, verbose_name='共有可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='spirit_enable_flg',
            field=models.BooleanField(default=False, verbose_name='霊媒可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mposition',
            name='vote_enable_flg',
            field=models.BooleanField(default=True, verbose_name='投票可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='speech_hear_mode',
            field=models.SmallIntegerField(choices=[(0, '発言・閲覧不可'), (1, '発言不可・他人発言のみ閲覧可'), (2, '発言可・自己発言のみ閲覧可'), (3, '発言可・自己・他人発言ともに閲覧可')], default=0, verbose_name='発言・閲覧モード'),
        ),
        migrations.AlterField(
            model_name='mpositionvoicesetting',
            name='voice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MVoiceType', verbose_name='発言種別'),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='message',
            field=models.TextField(blank=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='sequence_number',
            field=models.SmallIntegerField(default=0, verbose_name='連番'),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='system_message_name',
            field=models.CharField(max_length=100, verbose_name='システム文書名称'),
        ),
        migrations.AlterField(
            model_name='msysmessage',
            name='system_message_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MSysMessageSet', verbose_name='システム文章セット'),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='msysmessageset',
            name='system_message_set_name',
            field=models.CharField(max_length=100, verbose_name='システム文書セット名称'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='max_str_length',
            field=models.SmallIntegerField(default=0, verbose_name='最大文字数'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='max_voice_point',
            field=models.SmallIntegerField(default=0, verbose_name='最大ポイント数'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_number',
            field=models.SmallIntegerField(default=0, verbose_name='発言回数設定'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_point',
            field=models.SmallIntegerField(default=0, verbose_name='発言ポイント'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MVoiceSettingSet', verbose_name='発言設定セット'),
        ),
        migrations.AlterField(
            model_name='mvoicesetting',
            name='voice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType', verbose_name='発言種別'),
        ),
        migrations.AlterField(
            model_name='mvoicesettingset',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='mvoicesettingset',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='mvoicesettingset',
            name='display_order',
            field=models.IntegerField(verbose_name='並び順'),
        ),
        migrations.AlterField(
            model_name='mvoicesettingset',
            name='voice_type_set_name',
            field=models.CharField(max_length=100, verbose_name='発言設定セット名称'),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='commentary',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='prologue_speech_enable_flg',
            field=models.BooleanField(default=False, verbose_name='プロローグ発言可否フラグ'),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='voice_type_name',
            field=models.CharField(max_length=100, verbose_name='発言種別名称'),
        ),
        migrations.AlterField(
            model_name='mvoicetype',
            name='voice_type_symbol',
            field=models.CharField(blank=True, max_length=10, verbose_name='発言種別記号（例：人狼:*、独り言：-）'),
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='number',
            field=models.SmallIntegerField(verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.VillageOrganizationSet', verbose_name='編成セット'),
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='serial_number',
            field=models.SmallIntegerField(verbose_name='連番'),
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villageorganizationset',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='villageorganizationset',
            name='organization_set_name',
            field=models.CharField(max_length=100, verbose_name='編成セット名称'),
        ),
        migrations.AlterField(
            model_name='villageorganizationset',
            name='participant_number',
            field=models.SmallIntegerField(verbose_name='参加者数'),
        ),
        migrations.AlterField(
            model_name='villageorganizationset',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='character_name',
            field=models.CharField(max_length=30, verbose_name='キャラクタ名'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MChip', verbose_name='チップ'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='description',
            field=models.CharField(max_length=30, verbose_name='肩書'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='pl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.PLAccount', verbose_name='PL'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_position_id', to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '生存'), (1, '処刑死'), (2, '襲撃死'), (9, '突然死'), (10, '退村')], default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='system_user_flg',
            field=models.BooleanField(default=False, verbose_name='システム用ユーザーフラグ'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='village_denominated_flg',
            field=models.BooleanField(default=False, verbose_name='村建てフラグ'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='win_lose_class',
            field=models.SmallIntegerField(choices=[(0, '未決着'), (1, '勝利'), (2, '敗北'), (9, '突然死')], default=0, verbose_name='勝敗区分'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='wish_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_wish_position_id', to='pywolf.MPosition', verbose_name='希望役職'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='assault',
            field=models.CharField(blank=True, max_length=255, verbose_name='襲撃先ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='day_no',
            field=models.SmallIntegerField(default=0, verbose_name='日数番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='fortune',
            field=models.CharField(blank=True, max_length=255, verbose_name='占い先ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='guard',
            field=models.CharField(blank=True, max_length=255, verbose_name='護衛先ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='village_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant', verbose_name='村参加者'),
        ),
        migrations.AlterField(
            model_name='villageparticipantexeability',
            name='vote',
            field=models.CharField(blank=True, max_length=255, verbose_name='投票先ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='day_no',
            field=models.SmallIntegerField(default=0, verbose_name='日数番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='delete_flg',
            field=models.BooleanField(default=False, verbose_name='削除フラグ'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='good_pl',
            field=models.CharField(blank=True, max_length=255, verbose_name='イイねしたPL'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='system_voice_flg',
            field=models.BooleanField(default=False, verbose_name='システムメッセージフラグ'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='use_point',
            field=models.SmallIntegerField(verbose_name='使用発言ポイント'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='village_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant', verbose_name='村参加者ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='voice',
            field=models.TextField(blank=True, verbose_name='発言'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='voice_datetime',
            field=models.DateTimeField(verbose_name='発言日時'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='voice_number',
            field=models.SmallIntegerField(verbose_name='発言番号（種別毎）'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='voice_order',
            field=models.SmallIntegerField(verbose_name='発言順（村での通し番号）'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='voice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType', verbose_name='発言種別'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='day_no',
            field=models.SmallIntegerField(default=0, verbose_name='日数番号'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='village_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant', verbose_name='村参加者ID'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='voice_number_remain',
            field=models.SmallIntegerField(verbose_name='残り発言回数'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='voice_point_remain',
            field=models.SmallIntegerField(verbose_name='残り発言ポイント数'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='voice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType', verbose_name='発言種別'),
        ),
        migrations.AlterField(
            model_name='villageprogress',
            name='day_no',
            field=models.SmallIntegerField(default=0, verbose_name='日数番号'),
        ),
        migrations.AlterField(
            model_name='villageprogress',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villageprogress',
            name='village_status',
            field=models.SmallIntegerField(choices=[(0, 'プロローグ'), (1, '進行中'), (2, 'エピローグ'), (3, '終了'), (4, '廃村')], default=0, verbose_name='村状態'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='epilogue_limit_off_flg',
            field=models.BooleanField(default=True, verbose_name='エピローグ無制限発言フラグ'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='max_str_length',
            field=models.SmallIntegerField(default=0, verbose_name='最大文字数'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='max_voice_point',
            field=models.SmallIntegerField(default=0, verbose_name='最大ポイント数'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='prologue_limit_off_flg',
            field=models.BooleanField(default=False, verbose_name='プロローグ無制限発言フラグ'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='tomb_limit_off_flg',
            field=models.BooleanField(default=False, verbose_name='墓下無制限発言フラグ'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村番号'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='voice_number',
            field=models.SmallIntegerField(default=0, verbose_name='発言回数設定'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='voice_point',
            field=models.SmallIntegerField(default=0, verbose_name='発言ポイント'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='voice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MVoiceType', verbose_name='発言種別'),
        ),
    ]
