# Generated by Django 2.1.2 on 2018-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0024_auto_20181026_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='village_master_account',
            field=models.ForeignKey(on_delete=models.SET('削除されたID'), to='pywolf.PLAccount', verbose_name='村建てID'),
        ),
        # migrations.RemoveField(
        #     model_name='villageorganization',
        #     name='village_no',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='villageorganization',
        #     unique_together={('organization', 'serial_number')},
        # ),
        migrations.AlterUniqueTogether(
            name='villageorganizationset',
            unique_together=set(),
        ),
    ]
