# Generated by Django 2.1.2 on 2018-10-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0025_auto_20181031_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageparticipant',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_position_id', to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.RemoveField(
            model_name='villageorganization',
            name='village_no',
        ),
        migrations.AlterUniqueTogether(
            name='villageorganization',
            unique_together={('organization', 'serial_number')},
        ),
    ]
