# Generated by Django 2.1.2 on 2018-10-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0026_auto_20181031_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageparticipant',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='villageparticipant_position_id', to='pywolf.MPosition', verbose_name='役職'),
        ),
    ]
