# Generated by Django 2.1.2 on 2018-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0028_auto_20181031_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageparticipant',
            name='cancel_flg',
            field=models.BooleanField(default=False, verbose_name='退村フラグ'),
        ),
    ]
