# Generated by Django 2.1.2 on 2018-10-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0029_villageparticipant_cancel_flg'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageparticipant',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='連番'),
        ),
        migrations.AlterUniqueTogether(
            name='villageparticipant',
            unique_together={('village_no', 'pl', 'sequence')},
        ),
    ]
