# Generated by Django 2.1.2 on 2018-10-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0030_auto_20181031_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villageparticipantvoicestatus',
            unique_together={('village_participant', 'day_no', 'voice_type')},
        ),
    ]
