# Generated by Django 2.1.2 on 2018-11-02 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0031_auto_20181031_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='MStyleSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylesheet_name', models.CharField(max_length=100, verbose_name='スタイルシート名')),
                ('file_path', models.FileField(upload_to='', verbose_name='ファイルパス')),
                ('commentary', models.TextField(blank=True, verbose_name='説明')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': 'スタイルシート',
                'verbose_name_plural': 'スタイルシートマスタ',
            },
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/chips/', verbose_name='画像ファイルパス'),
        ),
        migrations.AlterField(
            model_name='morganization',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.AlterField(
            model_name='villageorganizationset',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AlterField(
            model_name='villageparticipant',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoice',
            name='village_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant', verbose_name='村参加者'),
        ),
        migrations.AlterField(
            model_name='villageparticipantvoicestatus',
            name='village_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.VillageParticipant', verbose_name='村参加者'),
        ),
        migrations.AlterField(
            model_name='villageprogress',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AlterField(
            model_name='villagevoicesetting',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AddField(
            model_name='placcount',
            name='select_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pywolf.MStyleSheet', verbose_name='選択スタイルシート'),
        ),
    ]
