# Generated by Django 2.1.2 on 2018-11-02 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0032_auto_20181102_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='MStyleSheetSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stylesheet_set_name', models.CharField(max_length=100, verbose_name='スタイルシートセット名称')),
                ('commentary', models.TextField(blank=True, verbose_name='説明')),
                ('display_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': 'スタイルシートセット',
                'verbose_name_plural': 'スタイルシートセットマスタ',
            },
        ),
        migrations.AddField(
            model_name='mstylesheet',
            name='sequence_number',
            field=models.SmallIntegerField(default=0, verbose_name='連番'),
        ),
        migrations.AddField(
            model_name='mstylesheet',
            name='stylesheet_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pywolf.MStyleSheetSet', verbose_name='スタイルシートセット'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='mstylesheet',
            unique_together={('stylesheet_set', 'sequence_number')},
        ),
    ]
