# Generated by Django 2.1.2 on 2018-11-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0033_auto_20181102_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvoicesettingset',
            old_name='voice_type_set_name',
            new_name='voice_setting_set_name',
        ),
        migrations.AlterField(
            model_name='mchip',
            name='image_file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/chips/', verbose_name='画像ファイルパス'),
        ),
        migrations.AlterField(
            model_name='mstylesheet',
            name='file_path',
            field=models.FileField(upload_to='pywolf/static/pywolf/', verbose_name='ファイルパス'),
        ),
        migrations.AlterModelTable(
            name='mchip',
            table='m_chip',
        ),
        migrations.AlterModelTable(
            name='mchipset',
            table='m_chip_set',
        ),
        migrations.AlterModelTable(
            name='morganization',
            table='m_organization',
        ),
        migrations.AlterModelTable(
            name='morganizationset',
            table='m_organization_set',
        ),
        migrations.AlterModelTable(
            name='mposition',
            table='m_position',
        ),
        migrations.AlterModelTable(
            name='mpositionvoicesetting',
            table='m_position_voice_setting',
        ),
        migrations.AlterModelTable(
            name='mstylesheet',
            table='m_stylesheet',
        ),
        migrations.AlterModelTable(
            name='mstylesheetset',
            table='m_stylesheet_set',
        ),
        migrations.AlterModelTable(
            name='msysmessage',
            table='m_system_message',
        ),
        migrations.AlterModelTable(
            name='msysmessageset',
            table='m_system_message_set',
        ),
        migrations.AlterModelTable(
            name='mvoicesetting',
            table='m_voice_setting',
        ),
        migrations.AlterModelTable(
            name='mvoicesettingset',
            table='m_voice_setting_set',
        ),
        migrations.AlterModelTable(
            name='mvoicetype',
            table='m_voice_type',
        ),
        migrations.AlterModelTable(
            name='placcount',
            table='pl_account',
        ),
        migrations.AlterModelTable(
            name='village',
            table='village',
        ),
        migrations.AlterModelTable(
            name='villageorganization',
            table='village_organization',
        ),
        migrations.AlterModelTable(
            name='villageorganizationset',
            table='village_organization_set',
        ),
        migrations.AlterModelTable(
            name='villageparticipant',
            table='village_participant',
        ),
        migrations.AlterModelTable(
            name='villageparticipantexeability',
            table='village_participant_exe_ability',
        ),
        migrations.AlterModelTable(
            name='villageparticipantvoice',
            table='village_participant_voice',
        ),
        migrations.AlterModelTable(
            name='villageparticipantvoicestatus',
            table='village_participant_voice_status',
        ),
        migrations.AlterModelTable(
            name='villageprogress',
            table='village_progress',
        ),
        migrations.AlterModelTable(
            name='villagevoicesetting',
            table='village_voice_setting',
        ),
    ]
