# Generated by Django 2.1.2 on 2018-11-08 06:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0034_auto_20181108_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOrganizationParticipantNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.SmallIntegerField(verbose_name='参加者数')),
            ],
            options={
                'verbose_name': '編成\u3000参加人数',
                'verbose_name_plural': '編成\u3000参加人数マスタ',
                'db_table': 'm_organization_participant_number',
            },
        ),
        migrations.CreateModel(
            name='MOrganizationPositionNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'verbose_name': '編成',
                'verbose_name_plural': '編成マスタ',
                'db_table': 'm_organization_position_number',
            },
        ),
        # migrations.AlterUniqueTogether(
        #     name='morganization',
        #     unique_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='morganization',
        #     name='organization',
        # ),
        # migrations.RemoveField(
        #     model_name='morganization',
        #     name='position_id',
        # ),
        # migrations.RemoveField(
        #     model_name='morganizationset',
        #     name='participant_number',
        # ),
        migrations.AlterField(
            model_name='village',
            name='lowest_number',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(99)], verbose_name='最低人数'),
        ),
        migrations.AlterField(
            model_name='village',
            name='max_number',
            field=models.SmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(99)], verbose_name='最大人数'),
        ),
        # migrations.DeleteModel(
        #     name='MOrganization',
        # ),
        migrations.AddField(
            model_name='MOrganizationPositionNumber',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MOrganizationSet', verbose_name='編成セット'),
        ),
        migrations.AddField(
            model_name='MOrganizationPositionNumber',
            name='participant_number_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MOrganizationParticipantNumber', verbose_name='参加人数'),
        ),
        migrations.AddField(
            model_name='MOrganizationPositionNumber',
            name='position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MPosition', verbose_name='役職'),
        ),
        migrations.AddField(
            model_name='morganizationparticipantnumber',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.MOrganizationSet', verbose_name='編成セット'),
        ),
        migrations.AlterUniqueTogether(
            name='MOrganizationPositionNumber',
            unique_together={('organization', 'participant_number_id', 'position_id')},
        ),
        migrations.AlterUniqueTogether(
            name='morganizationparticipantnumber',
            unique_together={('organization', 'participant_number')},
        ),
    ]
