# Generated by Django 2.1.2 on 2018-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0035_auto_20181108_1532'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='morganization',
        #     unique_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='morganization',
        #     name='organization',
        # ),
        # migrations.RemoveField(
        #     model_name='morganization',
        #     name='position_id',
        # ),
        # migrations.RemoveField(
        #     model_name='morganizationset',
        #     name='participant_number',
        # ),
        migrations.AddField(
            model_name='mchipset',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='並び順'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='morganizationset',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='並び順'),
            preserve_default=False,
        ),
        # migrations.DeleteModel(
        #     name='MOrganization',
        # ),
    ]
