# Generated by Django 2.1.2 on 2018-11-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0036_auto_20181108_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageOrganizationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.SmallIntegerField(verbose_name='参加者数')),
                ('delete_flg', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': '村編成設定',
                'verbose_name_plural': '村編成設定',
                'db_table': 'village_organization_setting',
            },
        ),
        migrations.AlterUniqueTogether(
            name='morganization',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='morganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='morganization',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='villageorganizationset',
            name='village_no',
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'get_latest_by': 'village_no', 'verbose_name': '村', 'verbose_name_plural': '村情報'},
        ),
        migrations.RemoveField(
            model_name='morganizationset',
            name='participant_number',
        ),
        migrations.AddField(
            model_name='village',
            name='organization_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.MOrganizationSet', verbose_name='編成セット(村作成時の設定)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villageorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pywolf.VillageOrganizationSetting', verbose_name='村編成設定'),
        ),
        migrations.DeleteModel(
            name='MOrganization',
        ),
        migrations.DeleteModel(
            name='VillageOrganizationSet',
        ),
        migrations.AddField(
            model_name='villageorganizationsetting',
            name='village_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pywolf.Village', verbose_name='村'),
        ),
        migrations.AlterUniqueTogether(
            name='villageorganization',
            unique_together={('organization', 'position')},
        ),
        migrations.RemoveField(
            model_name='villageorganization',
            name='serial_number',
        ),
    ]
