# Generated by Django 2.0.6 on 2018-11-10 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0037_auto_20181109_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placcount',
            name='select_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pywolf.MStyleSheetSet', verbose_name='選択スタイルシート'),
        ),
    ]
