# Generated by Django 2.1.2 on 2018-11-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0040_villageprogress_next_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villageprogress',
            name='next_update_datetime',
            field=models.DateTimeField(null=True, verbose_name='次回更新日時'),
        ),
    ]
