# Generated by Django 2.1.2 on 2018-11-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0041_auto_20181113_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='villageprogress',
            name='update_processing_lock',
            field=models.BooleanField(default=False, verbose_name='更新処理中ロック'),
        ),
    ]
