# Generated by Django 2.1.2 on 2018-11-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0042_villageprogress_update_processing_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchip',
            name='dummy_flg',
            field=models.BooleanField(default=False, verbose_name='ダミーキャラクタフラグ'),
        ),
        migrations.AddField(
            model_name='mchip',
            name='dummy_voice_first',
            field=models.TextField(null=True, verbose_name='ダミー発言：１日目'),
        ),
        migrations.AddField(
            model_name='mchip',
            name='dummy_voice_pro',
            field=models.TextField(null=True, verbose_name='ダミー発言：プロローグ'),
        ),
        migrations.AddField(
            model_name='village',
            name='dummy_character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pywolf.MChip', verbose_name='ダミーキャラクター'),
            preserve_default=False,
        ),
    ]
