# Generated by Django 2.1.2 on 2018-11-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0044_placcount_dummy_user_flg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villageparticipant',
            name='system_user_flg',
        ),
    ]
