# Generated by Django 2.1.2 on 2018-11-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0045_remove_villageparticipant_system_user_flg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchip',
            name='dummy_voice_first',
            field=models.TextField(blank=True, null=True, verbose_name='ダミー発言：１日目'),
        ),
        migrations.AlterField(
            model_name='mchip',
            name='dummy_voice_pro',
            field=models.TextField(blank=True, null=True, verbose_name='ダミー発言：プロローグ'),
        ),
    ]
