# Generated by Django 2.1.2 on 2018-11-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pywolf', '0046_auto_20181114_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='max_voice_line',
            field=models.IntegerField(default=20, verbose_name='発言最大行数'),
        ),
    ]
