from .index import index
from .village import village
from .voice import voice
from .login import login
from .logout import logout
from .vote import vote
from .entry import entry
from .entry_cancel import entry_cancel
from .fortune import fortune
